"""Extracts the stat effects of SpellItemEnchantment.dbc (frFR 3.3.5a client) into tests/data/enchant_stats.frFR.txt.

Usage, from the addon root:
    uv run --with mpyq python tests/extract_enchant_stats.py "../../../Data"

Running it again on the same client data writes the same file, byte for byte.
"""
import hashlib
import struct
import sys

from extract_ratings import read_file

DBC = "DBFilesClient\\SpellItemEnchantment.dbc"
OUTPUT = "tests/data/enchant_stats.frFR.txt"
# Fields (32-bit, from 0): 0 ID, 2-4 effect type, 5-7 effect amount (min), 11-13 effect argument, 16 frFR text.
FIELDS = 38
STAT_EFFECT = 5  # ITEM_ENCHANTMENT_TYPE_STAT: the argument is the ITEM_MOD_* stat number


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    archive, data = read_file(sys.argv[1], DBC)
    magic, records, fields, record_size, _ = struct.unpack("<4s4i", data[:20])
    if magic != b"WDBC" or fields != FIELDS or record_size != FIELDS * 4:
        sys.exit("format de SpellItemEnchantment.dbc inattendu : %r %d %d" % (magic, fields, record_size))
    strings = data[20 + records * record_size:]

    def text(offset):
        return strings[offset:strings.index(b"\0", offset)].decode("utf-8")

    out = [
        "# Generated by tests/extract_enchant_stats.py: do not edit.",
        "# Source: %s from Data/%s (md5 %s)" % (DBC, archive, hashlib.md5(data).hexdigest()),
        "# Fields (32-bit, from 0): 0 ID, 2-4 effect type (5 = stat), 5-7 amount, 11-13 stat number (ITEM_MOD_*), 16 frFR text.",
        "# One line per stat effect: ID<TAB>stat number<TAB>amount<TAB>text",
    ]
    for index in range(records):
        start = 20 + index * record_size
        row = struct.unpack("<%di" % FIELDS, data[start:start + record_size])
        for effect in range(3):
            if row[2 + effect] == STAT_EFFECT:
                out.append("%d\t%d\t%d\t%s" % (row[0], row[11 + effect], row[5 + effect], text(row[16])))
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")
    print("%s écrit (%d effets, %s)" % (OUTPUT, len(out) - 4, archive))


if __name__ == "__main__":
    main()
