"""Extracts the combat rating table of the frFR 3.3.5a client into PawnRatingLevelFactors.lua.

Usage, from the addon root:
    uv run --with mpyq python tests/extract_ratings.py "../../../Data"

Running it again on the same client data writes the same file, byte for byte.
"""
import hashlib
import os
import re
import struct
import sys

import mpyq

# Highest priority first, as the client loads them. Patch-Z.MPQ (server patch) holds neither file read here,
# so its exact rank doesn't matter for this script.
ARCHIVES = [
    "frFR/patch-frFR-3.MPQ", "frFR/patch-frFR-2.MPQ", "frFR/patch-frFR.MPQ",
    "Patch-Z.MPQ", "patch-3.MPQ", "patch-2.MPQ", "patch.MPQ",
    "frFR/lichking-locale-frFR.MPQ", "frFR/expansion-locale-frFR.MPQ", "frFR/locale-frFR.MPQ",
    "lichking.MPQ", "expansion.MPQ", "common-2.MPQ", "common.MPQ",
]
DBC = "DBFilesClient\\gtCombatRatings.dbc"
PAPERDOLL = "Interface\\FrameXML\\PaperDollFrame.lua"
OUTPUT = "PawnRatingLevelFactors.lua"
LEVELS_IN_DBC = 100
MAX_LEVEL = 80

# Pawn stat -> client constants. The first one gives the values; Pawn merges the others into the same stat,
# so they must scale exactly the same way with level.
STATS = [
    ("HitRating", ["CR_HIT_MELEE", "CR_HIT_RANGED", "CR_HIT_SPELL"]),
    ("CritRating", ["CR_CRIT_MELEE", "CR_CRIT_RANGED", "CR_CRIT_SPELL"]),
    ("HasteRating", ["CR_HASTE_MELEE", "CR_HASTE_RANGED", "CR_HASTE_SPELL"]),
    ("ExpertiseRating", ["CR_EXPERTISE"]),
    ("ArmorPenetration", ["CR_ARMOR_PENETRATION"]),
    ("DefenseRating", ["CR_DEFENSE_SKILL"]),
    ("DodgeRating", ["CR_DODGE"]),
    ("ParryRating", ["CR_PARRY"]),
    ("BlockRating", ["CR_BLOCK"]),
    ("ResilienceRating", ["CR_CRIT_TAKEN_MELEE"]),
    # Ratings that only apply to spells, melee or ranged attacks (PawnRestrictedRatingStats in Pawn.lua).
    ("SpellHitRating", ["CR_HIT_SPELL"]),
    ("SpellCritRating", ["CR_CRIT_SPELL"]),
    ("SpellHasteRating", ["CR_HASTE_SPELL"]),
    ("MeleeHitRating", ["CR_HIT_MELEE"]),
    ("MeleeCritRating", ["CR_CRIT_MELEE"]),
    ("MeleeHasteRating", ["CR_HASTE_MELEE"]),
    ("RangedHitRating", ["CR_HIT_RANGED"]),
    ("RangedCritRating", ["CR_CRIT_RANGED"]),
    ("RangedHasteRating", ["CR_HASTE_RANGED"]),
]


def read_file(data_dir, name):
    """Returns (archive, bytes) from the highest-priority archive that holds name."""
    for archive in ARCHIVES:
        path = os.path.join(data_dir, archive)
        if not os.path.exists(path):
            continue
        data = mpyq.MPQArchive(path, listfile=False).read_file(name)
        if data:
            return archive, data
    sys.exit("introuvable dans les MPQ : " + name)


def read_constants(text):
    return {name: int(value) for name, value in re.findall(r"^(CR_[A-Z_]+)\s*=\s*(\d+);", text, re.M)}


def read_dbc(data):
    magic, records, fields, record_size, _ = struct.unpack("<4s4i", data[:20])
    if magic != b"WDBC" or fields != 1 or record_size != 4 or records % LEVELS_IN_DBC != 0:
        sys.exit("format de gtCombatRatings.dbc inattendu : %r %d %d %d" % (magic, records, fields, record_size))
    return struct.unpack("<%df" % records, data[20:20 + records * 4])


def lua_number(value):
    text = "%.4f" % round(value, 4)
    return text.rstrip("0").rstrip(".")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    data_dir = sys.argv[1]
    dbc_archive, dbc = read_file(data_dir, DBC)
    lua_archive, lua = read_file(data_dir, PAPERDOLL)
    constants = read_constants(lua.decode("utf-8", "replace"))
    values = read_dbc(dbc)

    def points(constant, level):
        if constant not in constants:
            sys.exit("constante absente de PaperDollFrame.lua : " + constant)
        return values[(constants[constant] - 1) * LEVELS_IN_DBC + (level - 1)]

    for stat, names in STATS:
        for level in range(1, MAX_LEVEL + 1):
            reference = points(names[0], MAX_LEVEL) / points(names[0], level)
            for name in names[1:]:
                ratio = points(name, MAX_LEVEL) / points(name, level)
                if abs(ratio - reference) > 1e-4 * reference:
                    sys.exit("%s : %s et %s n'évoluent pas pareil au niveau %d (%.6f / %.6f), décision à prendre"
                             % (stat, names[0], name, level, reference, ratio))

    out = [
        "-- Generated by tests/extract_ratings.py: do not edit.",
        "-- Regenerate from the addon root: uv run --with mpyq python tests/extract_ratings.py \"../../../Data\"",
        "-- Values: %s from Data/%s (md5 %s)" % (DBC, dbc_archive, hashlib.md5(dbc).hexdigest()),
        "-- CR_* constants: %s from Data/%s (md5 %s)" % (PAPERDOLL, lua_archive, hashlib.md5(lua).hexdigest()),
        "-- PawnRatingPointsPerPercent[Stat][Level]: rating points for 1% (1 point of defense or expertise)",
        "-- at that level, rounded to 4 decimals. Melee, ranged and spell variants scale the same way (checked).",
        "",
        "PawnRatingPointsPerPercent =",
        "{",
    ]
    for stat, names in STATS:
        out.append("\t[\"%s\"] = { -- %s = %d" % (stat, names[0], constants[names[0]]))
        row = [lua_number(points(names[0], level)) for level in range(1, MAX_LEVEL + 1)]
        for start in range(0, MAX_LEVEL, 10):
            out.append("\t\t" + ", ".join(row[start:start + 10]) + ",")
        out.append("\t},")
    out.append("}")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")
    print("%s écrit (valeurs : %s, constantes : %s)" % (OUTPUT, dbc_archive, lua_archive))


if __name__ == "__main__":
    main()
