"""Extracts the classes of the frFR 3.3.5a client into tests/data/classes.frFR.txt (ChrClasses.dbc): ID, token, male and
female names.  The client fills LOCALIZED_CLASS_NAMES_MALE / _FEMALE with these names (FrameXML Constants.lua).

Usage, from the addon root:
    uv run --with mpyq python tests/extract_classes.py "../../../Data"

Running it again on the same client data writes the same file, byte for byte.
"""
import hashlib
import struct
import sys

sys.dont_write_bytecode = True  # importing extract_ratings would otherwise leave tests/__pycache__ behind
from extract_ratings import read_file

DBC = "DBFilesClient\\ChrClasses.dbc"
OUTPUT = "tests/data/classes.frFR.txt"
# ChrClasses.dbc fields (32-bit, from 0): 0 ID, 23 frFR female name, 40 frFR male name, 55 token.
FIELDS = 60


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    archive, data = read_file(sys.argv[1], DBC)
    magic, records, fields, record_size, _ = struct.unpack("<4s4i", data[:20])
    if magic != b"WDBC" or fields != FIELDS or record_size != FIELDS * 4:
        sys.exit("format de ChrClasses.dbc inattendu : %r %d %d" % (magic, fields, record_size))
    strings = data[20 + records * record_size:]

    def text(offset):
        return strings[offset:strings.index(b"\0", offset)].decode("utf-8")

    out = [
        "# Generated by tests/extract_classes.py: do not edit.",
        "# Source: %s from Data/%s (md5 %s)" % (DBC, archive, hashlib.md5(data).hexdigest()),
        "# Fields (32-bit, from 0): 0 ID, 23 female name, 40 male name, 55 token. An empty female name is empty in the DBC.",
        "# One line per class: ID<TAB>token<TAB>male name<TAB>female name",
    ]
    for index in range(records):
        start = 20 + index * record_size
        row = struct.unpack("<%di" % FIELDS, data[start:start + record_size])
        out.append("%d\t%s\t%s\t%s" % (row[0], text(row[55]), text(row[40]), text(row[23])))
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")
    print("%s écrit (%d classes, %s)" % (OUTPUT, len(out) - 4, archive))


if __name__ == "__main__":
    main()
