"""Extracts the gems of the frFR 3.3.5a client into tests/data/gems.frFR.txt: for each gem enchantment of
SpellItemEnchantment.dbc, the gem item, its color (GemProperties.dbc), its stat effects and its text.

Usage, from the addon root:
    uv run --with mpyq python tests/extract_gems.py "../../../Data"

Running it again on the same client data writes the same file, byte for byte.
"""
import hashlib
import struct
import sys

sys.dont_write_bytecode = True  # importing extract_ratings would otherwise leave tests/__pycache__ behind
from extract_ratings import read_file

ENCHANTS = "DBFilesClient\\SpellItemEnchantment.dbc"
GEMS = "DBFilesClient\\GemProperties.dbc"
OUTPUT = "tests/data/gems.frFR.txt"
# SpellItemEnchantment.dbc fields (32-bit, from 0): 0 ID, 2-4 effect type, 5-7 amount, 11-13 stat number (ITEM_MOD_*),
# 16 frFR text, 33 gem item (0 for enchantments that don't come from a gem).
ENCHANT_FIELDS = 38
# GemProperties.dbc fields: 1 enchantment, 4 color (1 meta, 2 red, 4 yellow, 8 blue; a gem of several colors adds them).
GEM_FIELDS = 5
STAT_EFFECT = 5  # ITEM_ENCHANTMENT_TYPE_STAT


def read_dbc(data_dir, name, fields):
    archive, data = read_file(data_dir, name)
    magic, records, count, record_size, _ = struct.unpack("<4s4i", data[:20])
    if magic != b"WDBC" or count != fields or record_size != fields * 4:
        sys.exit("format de %s inattendu : %r %d %d" % (name, magic, count, record_size))
    rows = [struct.unpack("<%di" % fields, data[20 + i * record_size:20 + (i + 1) * record_size]) for i in range(records)]
    return archive, data, rows, data[20 + records * record_size:]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    enchant_archive, enchant_data, enchants, strings = read_dbc(sys.argv[1], ENCHANTS, ENCHANT_FIELDS)
    gem_archive, gem_data, gems, _ = read_dbc(sys.argv[1], GEMS, GEM_FIELDS)
    color = {row[1]: row[4] for row in gems}

    def text(offset):
        return strings[offset:strings.index(b"\0", offset)].decode("utf-8")

    out = [
        "# Generated by tests/extract_gems.py: do not edit.",
        "# Source: %s from Data/%s (md5 %s)" % (ENCHANTS, enchant_archive, hashlib.md5(enchant_data).hexdigest()),
        "# Source: %s from Data/%s (md5 %s)" % (GEMS, gem_archive, hashlib.md5(gem_data).hexdigest()),
        "# SpellItemEnchantment fields: 2-4 effect type (5 = stat), 5-7 amount, 11-13 stat number, 16 text, 33 gem item.",
        "# GemProperties fields: 1 enchantment, 4 color (1 meta, 2 red, 4 yellow, 8 blue, added for several colors).",
        "# One line per gem enchantment: gem item<TAB>color<TAB>stat number:amount[,...]<TAB>text",
    ]
    for row in enchants:
        if row[33]:
            effects = ["%d:%d" % (row[11 + k], row[5 + k]) for k in range(3) if row[2 + k] == STAT_EFFECT]
            out.append("%d\t%d\t%s\t%s" % (row[33], color.get(row[0], 0), ",".join(effects), text(row[16])))
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")
    print("%s écrit (%d gemmes)" % (OUTPUT, len(out) - 6))


if __name__ == "__main__":
    main()
